# Remap prefix to Ctrl-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Enable mouse support
set -g mouse on

# Set the base index for windows to 1
set -g base-index 1

# Set the base index for panes to 1
setw -g pane-base-index 1

# Use vi mode in copy mode
setw -g mode-keys vi

# Enable 256 color support
set -g default-terminal "screen-256color"

# Reload tmux config with Ctrl-a r
unbind r
bind r source-file ~/.tmux.conf

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

set-option -g status-position bottom

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Catppuccin mocha palette
set -g status-style "bg=#1e1e2e,fg=#cba6f7"
set -g status-left "#[bg=#313244,fg=#cba6f7] #S #[default] "
set -g status-right "#[bg=#313244,fg=#b4befe] %H:%M #[default]"
set -g window-status-format "#[fg=#6c7086] #I:#W "
set -g window-status-current-format "#[bg=#313244,fg=#cba6f7,bold] #I:#W "
set -g status-left-length 30
set -g status-right-length 20

run '~/.tmux/plugins/tpm/tpm'
